export enum routes {
  //auth
  ONBOARD = 'ONBOARD',
  SIGN_IN = 'SIGN_IN',
  CREATE_ACCOUNT = 'CREATE_ACCOUNT',
  LOBBY = 'LOBBY',
  UPDATE_PROFILE = 'UPDATE_PROFILE',
  BOTTOM_TAB = 'BOTTOM_TAB',
  HOME = 'HOME',
  HISTORY = 'HISTORY',
  CONTACT = 'CONTACT',
  SETTING = 'SETTING',
  DETAIL = 'DETAIL',
  SUPPORT = 'SUPPORT',

  // Screen home GV

  NOTIFICATION_SUPPORT = 'NOTIFICATION_SUPPORT',
  // Screen contact GV
  DETAILCONTACT = 'DETAILCONTACT',
  ITEMCONTACT = 'ITEMCONTACT',
  CREATE_REPORT = 'CREATE_REPORT',
  UP_IMAGE = 'UP_IMAGE',

  // Bottom tab Manager
  BOTTOMMANAGER = 'BOTTOMMANAGER',
  HOMEMANAGER = 'HOME',
  HISTORYMANAGER = 'HISTORY',
  SETTINGMANAGER = 'SETTING',
  // Screen home manager
  ACHIEVEMENT = 'ACHIEVEMENT',
  EVENT = 'EVENT',
  INCIDENT = 'INCIDENT',
  PERSONNEL = 'PERSONNEL',
  DETAILPERSONAL = 'DETAILPERSONAL',
  ROOMCHECKING = 'ROOMCHECKING',
  STATISTICAL = 'STATISTICAL',
  MYPROFILE = 'MYPROFILE',

  // Bottom tab NVHC
  BOTTOMNVHC = 'BOTTOMNVHC',
  HOMENVHC = 'HOME',
  HISTORYNVHC = 'HISTORY',
  SETTINGNVHC = 'SETTING',

  // Screen NVHC
  PROBLEM = 'PROBLEM',
  DETAILPROBLEM = 'DETAILPROBLEM',
  DONEPROBLEM = 'DONEPROBLEM',
  TIME_LINE_NVHC = 'TIME_LINE_NVHC',
}
