export enum routes {
  //auth
  ONBOARD = 'ONBOARD',
  LOBBY = 'LOBBY',
  SIGN_IN = 'SIGN_IN',

  // Bottom tab GV
  BOTTOM_TAB = 'BOTTOM_TAB',
  HOME = 'HOME',
  HISTORY = 'HISTORY',
  CONTACT = 'CONTACT',
  SETTING = 'SETTING',

  // Bottom tab Manager
  BOTTOMMANAGER = 'BOTTOMMANAGER',
  HOMEMANAGER = 'HOME',
  HISTORYMANAGER = 'HISTORY',
  SETTINGMANAGER = 'SETTING',
  // Screen home manager
  ACHIEVEMENT = 'ACHIEVEMENT',
  EVENT = 'EVENT',
  INCIDENT = 'INCIDENT',
  PERSONNEL = 'PERSONNEL',
  ROOMCHECKING = 'ROOMCHECKING',
  STATISTICAL = 'STATISTICAL',

  REPORT = 'REPORT',
  
  
}
